/* Auto-generated by gen_globals.py - DO NOT EDIT */
/* GameGlobals struct: all game globals in one packed block */
/* Matches original PILOTS.EXE data section layout */

#pragma pack(push, 1)
struct GameGlobals {
    /* +0x0000 (0x410074) */ char g_CursorObject[16];
    /* +0x0010 (0x410084) */ char g_DirFlagRemap_Rotate90CCW[16];
    /* +0x0020 (0x410094) */ char g_DirFlagRemap_Rotate180[16];
    /* +0x0030 (0x4100A4) */ char g_DirFlagRemap_Rotate90CW[16];
    /* +0x0040 (0x4100B4) */ char g_DirFlagRemap_FlipHorizontal[16];
    /* +0x0050 (0x4100C4) */ char g_DirFlagRemap_ReflectAntiDiag[16];
    /* +0x0060 (0x4100D4) */ char g_DirFlagRemap_FlipVertical[16];
    /* +0x0070 (0x4100E4) */ char g_DirFlagRemap_ReflectDiag[16];
    /* +0x0080 (0x4100F4) */ MoveDirectionHandler g_SpriteTransformTable[8];
    /* +0x00A0 (0x410114) */ MoveDirectionHandler g_TileMatchHandlers[16];
    /* +0x00E0 (0x410154) */ short g_SpriteVariantTable_2A;
    /* +0x00E2 (0x410156) */ short g_SpriteVariantTable_2B;
    /* +0x00E4 (0x410158) */ int g_SpriteVariantTable_2C;
    /* +0x00E8 (0x41015C) */ int g_SpriteVariantTable_3A;
    /* +0x00EC (0x410160) */ short g_SpriteVariantTable_2D;
    /* +0x00EE (0x410162) */ short g_SpriteVariantTable_2E;
    /* +0x00F0 (0x410164) */ int g_SpriteVariantTable_3B;
    /* +0x00F4 (0x410168) */ int g_SpriteVariantTable_2F;
    /* +0x00F8 (0x41016C) */ int g_SpriteVariantTable_3C;
    /* +0x00FC (0x410170) */ int g_SpriteVariantTable_3D;
    /* +0x0100 (0x410174) */ int g_SpriteVariantTable_4A;
    /* +0x0104 (0x410178) */ MoveDirectionHandler g_MoveDirectionHandlers[16];
    /* +0x0144 (0x4101B8) */ char _crt_jpt_403FDD[16]; /* CRT/skip */
    /* +0x0154 (0x4101C8) */ int g_RandomSeed;
    /* +0x0158 (0x4101CC) */ char aInsufficientMe[24];
    /* +0x0170 (0x4101E4) */ char aInvalidGameDat[40];
    /* +0x0198 (0x41020C) */ char dword_41020C[32];
    /* +0x01B8 (0x41022C) */ int dword_41022C;
    /* +0x01BC (0x410230) */ int dword_410230;
    /* +0x01C0 (0x410234) */ int dword_410234;
    /* +0x01C4 (0x410238) */ char dword_410238[52];
    /* +0x01F8 (0x41026C) */ char _crt_jpt_40570B[44]; /* CRT/skip */
    /* +0x0224 (0x410298) */ char byte_410298[44];
    /* +0x0250 (0x4102C4) */ char aMoviePlaybackE[24];
    /* +0x0268 (0x4102DC) */ char _crt_jpt_4062D2[28]; /* CRT/skip */
    /* +0x0284 (0x4102F8) */ char _crt_jpt_406871[20]; /* CRT/skip */
    /* +0x0298 (0x41030C) */ int (*g_NativeFuncTable[57])();
    /* +0x037C (0x4103F0) */ char g_MirrorDirectionTable[8];
    /* +0x0384 (0x4103F8) */ char _crt_jpt_407154[20]; /* CRT/skip */
    /* +0x0398 (0x41040C) */ char _crt_jpt_40727C[20]; /* CRT/skip */
    /* +0x03AC (0x410420) */ char _crt_jpt_407507[24]; /* CRT/skip */
    /* +0x03C4 (0x410438) */ char _crt_jpt_4083B9[36]; /* CRT/skip */
    /* +0x03E8 (0x41045C) */ char _crt_jpt_40845D[44]; /* CRT/skip */
    /* +0x0414 (0x410488) */ char _crt_jpt_40853D[44]; /* CRT/skip */
    /* +0x0440 (0x4104B4) */ char _crt_jpt_4087D6[16]; /* CRT/skip */
    /* +0x0450 (0x4104C4) */ char _crt_jpt_408814[32]; /* CRT/skip */
    /* +0x0470 (0x4104E4) */ char g_Format[16];
    /* +0x0480 (0x4104F4) */ char _crt_jpt_408E7C[224]; /* CRT/skip */
    /* +0x0560 (0x4105D4) */ char funcs_409620[16];
    /* +0x0570 (0x4105E4) */ int (*g_pfnWriteWaveBuffer)();
    /* +0x0574 (0x4105E8) */ int (*g_pfnStartMidiPlayback)();
    /* +0x0578 (0x4105EC) */ int (*g_pfnResetWave)();
    /* +0x057C (0x4105F0) */ int (*g_pfnStopMidiPlayback)();
    /* +0x0580 (0x4105F4) */ int (*g_pfnGetWaveVolume)();
    /* +0x0584 (0x4105F8) */ int (*g_pfnGetMidiVolume)();
    /* +0x0588 (0x4105FC) */ int (*g_pfnGetNextWaveBuffer)();
    /* +0x058C (0x410600) */ int (*g_pfnPauseWave)();
    /* +0x0590 (0x410604) */ int (*g_pfnResumeWave)();
    /* +0x0594 (0x410608) */ int (*g_pfnSetWaveVolume)();
    /* +0x0598 (0x41060C) */ int (*g_pfnSetMidiVolume)();
    /* +0x059C (0x410610) */ int (*g_pfnCleanupMultimedia)();
    /* +0x05A0 (0x410614) */ char aGmwDll[8];
    /* +0x05A8 (0x41061C) */ char aUtunregister[13];
    /* +0x05B5 (0x410629) */ char ProcName[11];
    /* +0x05C0 (0x410634) */ char LibFileName[16];
    /* +0x05D0 (0x410644) */ char g_bmi[552];
    /* +0x07F8 (0x41086C) */ char aGameMakerPlaye[18];
    /* +0x080A (0x41087E) */ char aHlp[6];
    /* +0x0810 (0x410884) */ char RootPathName[4];
    /* +0x0814 (0x410888) */ char aBmp[5];
    /* +0x0819 (0x41088D) */ char aAvi[5];
    /* +0x081E (0x410892) */ short asc_410892;
    /* +0x0820 (0x410894) */ char aInvalidMovieBa[33];
    /* +0x0841 (0x4108B5) */ char aIntro[6];
    /* +0x0847 (0x4108BB) */ char aGameRequiresLa[29];
    /* +0x0864 (0x4108D8) */ char ClassName[11];
    /* +0x086F (0x4108E3) */ char ModuleName[10];
    /* +0x0879 (0x4108ED) */ char aCreatedibsecti[231];
    /* +0x0960 (0x4109D4) */ char xmmword_4109D4[16];
    /* +0x0970 (0x4109E4) */ char aSDS[8];
    /* +0x0978 (0x4109EC) */ char g_SubStr[5];
    /* +0x097D (0x4109F1) */ char aSS[267];
    /* +0x0A88 (0x410AFC) */ char _crt_aFloatingPointN[32]; /* CRT/skip */
    /* +0x0AA8 (0x410B1C) */ char _crt_stru_410B1C[12]; /* CRT/skip */
    /* +0x0AB4 (0x410B28) */ char _crt_byte_410B28[60]; /* CRT/skip */
    /* +0x0AF0 (0x410B64) */ char _crt_hFile[4]; /* CRT/skip */
    /* +0x0AF4 (0x410B68) */ char _crt_dword_410B68[4]; /* CRT/skip */
    /* +0x0AF8 (0x410B6C) */ char _crt_dword_410B6C[232]; /* CRT/skip */
    /* +0x0BE0 (0x410C54) */ char _crt_dword_410C54[4]; /* CRT/skip */
    /* +0x0BE4 (0x410C58) */ char _crt_word_410C58[2]; /* CRT/skip */
    /* +0x0BE6 (0x410C5A) */ char _crt_word_410C5A[2]; /* CRT/skip */
    /* +0x0BE8 (0x410C5C) */ char _crt_aZx[24]; /* CRT/skip */
    /* +0x0C00 (0x410C74) */ char _crt_dword_410C74[4]; /* CRT/skip */
    /* +0x0C04 (0x410C78) */ char _crt_dword_410C78[4]; /* CRT/skip */
    /* +0x0C08 (0x410C7C) */ char _crt_word_410C7C[6]; /* CRT/skip */
    /* +0x0C0E (0x410C82) */ char _crt_dword_410C82[4]; /* CRT/skip */
    /* +0x0C12 (0x410C86) */ char _crt_word_410C86[4]; /* CRT/skip */
    /* +0x0C16 (0x410C8A) */ char _crt_word_410C8A[5]; /* CRT/skip */
    /* +0x0C1B (0x410C8F) */ char _crt_aSemaphoreError[20]; /* CRT/skip */
    /* +0x0C2F (0x410CA3) */ char _crt_aNotEnoughMemor[22]; /* CRT/skip */
    /* +0x0C45 (0x410CB9) */ char _crt_String[4]; /* CRT/skip */
    /* +0x0C49 (0x410CBD) */ char _crt_dword_410CBD[4]; /* CRT/skip */
    /* +0x0C4D (0x410CC1) */ char _crt_dword_410CC1[38]; /* CRT/skip */
    /* +0x0C73 (0x410CE7) */ char _crt_dword_410CE7[121]; /* CRT/skip */
    /* +0x0CEC (0x410D60) */ char _crt_dword_410D60[4]; /* CRT/skip */
    /* +0x0CF0 (0x410D64) */ char _crt_dword_410D64[4]; /* CRT/skip */
    /* +0x0CF4 (0x410D68) */ char _crt_dword_410D68[4]; /* CRT/skip */
    /* +0x0CF8 (0x410D6C) */ char _crt_dword_410D6C[4]; /* CRT/skip */
    /* +0x0CFC (0x410D70) */ char _crt_Str[12]; /* CRT/skip */
    /* +0x0D08 (0x410D7C) */ char _crt_asc_410D7C[2]; /* CRT/skip */
    /* +0x0D0A (0x410D7E) */ char _crt_AppName[7]; /* CRT/skip */
    /* +0x0D11 (0x410D85) */ char _crt_KeyName[8]; /* CRT/skip */
    /* +0x0D19 (0x410D8D) */ char _crt_Default[6]; /* CRT/skip */
    /* +0x0D1F (0x410D93) */ char _crt_aWin32sIni_0[12]; /* CRT/skip */
    /* +0x0D2B (0x410D9F) */ char _crt_Text[122]; /* CRT/skip */
    /* +0x0DA5 (0x410E19) */ char _crt_Caption[15]; /* CRT/skip */
    /* +0x0DB4 (0x410E28) */ char _crt_g_CommandLine[8]; /* CRT/skip */
    /* +0x0DBC (0x410E30) */ char _crt_dword_410E30[4]; /* CRT/skip */
    /* +0x0DC0 (0x410E34) */ char _crt_aThreadError[20]; /* CRT/skip */
    /* +0x0DD4 (0x410E48) */ char _crt_aOutOfMemory[14]; /* CRT/skip */
    /* +0x0DE2 (0x410E56) */ char _crt_asc_410E56[2]; /* CRT/skip */
    /* +0x0DE4 (0x410E58) */ char _crt_asc_410E58[4]; /* CRT/skip */
    /* +0x0DE8 (0x410E5C) */ char _crt_dword_410E5C[204]; /* CRT/skip */
    /* +0x0EB4 (0x410F28) */ char _crt_aSDS_0[7]; /* CRT/skip */
    /* +0x0EBB (0x410F2F) */ char _crt_tz_env_name[3]; /* CRT/skip */
    /* +0x0EBE (0x410F32) */ char _crt_default_dst_name[4]; /* CRT/skip */
    /* +0x0EC2 (0x410F36) */ char _crt_default_std_name[6]; /* CRT/skip */
    /* +0x0EC8 (0x410F3C) */ char _crt_dword_410F3C[4]; /* CRT/skip */
    /* +0x0ECC (0x410F40) */ char _crt_dword_410F40[4]; /* CRT/skip */
    /* +0x0ED0 (0x410F44) */ char _crt_dword_410F44[4]; /* CRT/skip */
    /* +0x0ED4 (0x410F48) */ char _crt_dword_410F48[4]; /* CRT/skip */
    /* +0x0ED8 (0x410F4C) */ char _crt_dword_410F4C[236]; /* CRT/skip */
    /* +0x0FC4 (0x411038) */ char _crt_byte_411038[260]; /* CRT/skip */
    /* +0x10C8 (0x41113C) */ char aA[4];
    /* +0x10CC (0x411140) */ char _crt_dword_411140[4]; /* CRT/skip */
    /* +0x10D0 (0x411144) */ char _crt_Block[4]; /* CRT/skip */
    /* +0x10D4 (0x411148) */ char _crt_g_BuildEnvironCallback[4]; /* CRT/skip */
    /* +0x10D8 (0x41114C) */ char _crt_off_41114C[8]; /* CRT/skip */
    /* +0x10E0 (0x411154) */ char _crt_off_411154[8]; /* CRT/skip */
    /* +0x10E8 (0x41115C) */ int g_MouseX;
    /* +0x10EC (0x411160) */ int g_MouseY;
    /* +0x10F0 (0x411164) */ int g_CameraOffsetX;
    /* +0x10F4 (0x411168) */ int g_CameraOffsetY;
    /* +0x10F8 (0x41116C) */ int g_DirtyRegionsList;
    /* +0x10FC (0x411170) */ RenderObject * g_LastCheckedRenderObject;
    /* +0x1100 (0x411174) */ char g_jmpbuf[64];
    /* +0x1140 (0x4111B4) */ char g_TileMapModified;
    /* +0x1141 (0x4111B5) */ char g_InputState[4];
    /* +0x1145          */ char _trail_g_InputState[3];
    /* +0x1148 (0x4111BC) */ char g_RandomChoiceArray[1024];
    /* +0x1548 (0x4115BC) */ int g_MemoryPoolStart;
    /* +0x154C (0x4115C0) */ int g_MemoryPoolCurrent;
    /* +0x1550 (0x4115C4) */ int g_MemoryPoolAvailable;
    /* +0x1554 (0x4115C8) */ int dword_4115C8;
    /* +0x1558          */ char _trail_dword_4115C8[152];
    /* +0x15F0 (0x411664) */ int g_BufferSize;
    /* +0x15F4 (0x411668) */ int g_FileBufferSize;
    /* +0x15F8 (0x41166C) */ int g_BufferPtr;
    /* +0x15FC (0x411670) */ int g_DataOffset;
    /* +0x1600 (0x411674) */ int g_IndexTableOffset;
    /* +0x1604 (0x411678) */ int g_MaxResourceIndex;
    /* +0x1608 (0x41167C) */ int g_TemplateDataSize;
    /* +0x160C (0x411680) */ int g_DecompressedDataSize;
    /* +0x1610 (0x411684) */ char g_CurrentOpcode;
    /* +0x1611          */ char _trail_g_CurrentOpcode[3];
    /* +0x1614 (0x411688) */ int g_TemplateDataBuffer;
    /* +0x1618 (0x41168C) */ int g_opcodeDataPtr;
    /* +0x161C (0x411690) */ int g_CurrentScenePtr;
    /* +0x1620 (0x411694) */ int g_ActiveSnapshotIndex;
    /* +0x1624 (0x411698) */ char byte_411698;
    /* +0x1625 (0x411699) */ char g_FontRenderFlags;
    /* +0x1626          */ char _trail_g_FontRenderFlags[2];
    /* +0x1628 (0x41169C) */ int g_CachedSpriteOffset;
    /* +0x162C (0x4116A0) */ int g_MaxDeferredLoadSize;
    /* +0x1630 (0x4116A4) */ int g_SpriteDataBuffer;
    /* +0x1634 (0x4116A8) */ int g_fileOffset;
    /* +0x1638 (0x4116AC) */ char video_command_type;
    /* +0x1639 (0x4116AD) */ char video_chunk_type;
    /* +0x163A (0x4116AE) */ char has_low_dword;
    /* +0x163B (0x4116AF) */ char has_high_dword;
    /* +0x163C (0x4116B0) */ __int64 chunk_data_qword;
    /* +0x1644 (0x4116B8) */ int video_repeat_count;
    /* +0x1648 (0x4116BC) */ int video_file_offset;
    /* +0x164C (0x4116C0) */ int target_frame_delay;
    /* +0x1650 (0x4116C4) */ int compressed_buffer_size;
    /* +0x1654 (0x4116C8) */ int compressed_buffer;
    /* +0x1658 (0x4116CC) */ int frame_data_size;
    /* +0x165C (0x4116D0) */ int frame_data_buffer;
    /* +0x1660 (0x4116D4) */ int palette_size;
    /* +0x1664 (0x4116D8) */ int palette_buffer;
    /* +0x1668 (0x4116DC) */ int sound_data_size;
    /* +0x166C (0x4116E0) */ int sound_data_buffer;
    /* +0x1670 (0x4116E4) */ int music_data_size;
    /* +0x1674 (0x4116E8) */ int music_data_buffer;
    /* +0x1678 (0x4116EC) */ char sound_playing_flag;
    /* +0x1679 (0x4116ED) */ char music_playing_flag;
    /* +0x167A (0x4116EE) */ char video_paused_flag;
    /* +0x167B          */ char _trail_video_paused_flag[1];
    /* +0x167C (0x4116F0) */ int frame_x_offset;
    /* +0x1680 (0x4116F4) */ int frame_y_offset;
    /* +0x1684 (0x4116F8) */ int frame_width;
    /* +0x1688 (0x4116FC) */ int frame_height;
    /* +0x168C (0x411700) */ char frame_ready_flag;
    /* +0x168D          */ char _trail_frame_ready_flag[3];
    /* +0x1690 (0x411704) */ int last_frame_time;
    /* +0x1694 (0x411708) */ int frame_counter;
    /* +0x1698 (0x41170C) */ char skip_frame_counter;
    /* +0x1699          */ char _trail_skip_frame_counter[3];
    /* +0x169C (0x411710) */ char byte_411710;
    /* +0x169D          */ char _trail_byte_411710[3];
    /* +0x16A0 (0x411714) */ int g_TextCommandPtr;
    /* +0x16A4 (0x411718) */ int g_TextFontIndex;
    /* +0x16A8 (0x41171C) */ int g_TextRenderX;
    /* +0x16AC (0x411720) */ int g_TextRenderY;
    /* +0x16B0 (0x411724) */ int g_TextCharRangePtr;
    /* +0x16B4 (0x411728) */ char g_TextInputBuffer[256];
    /* +0x17B4 (0x411828) */ int g_TextCharacterObjects[255];
    /* +0x1BB0 (0x411C24) */ int g_TextInputLength;
    /* +0x1BB4 (0x411C28) */ int g_TextInputMaxLength;
    /* +0x1BB8 (0x411C2C) */ int * g_TextInputTargetPtr;
    /* +0x1BBC (0x411C30) */ char g_TextInputMode;
    /* +0x1BBD (0x411C31) */ char g_TextInputActive;
    /* +0x1BBE (0x411C32) */ char g_TextInputNumericMode;
    /* +0x1BBF          */ char _trail_g_TextInputNumericMode[1];
    /* +0x1BC0 (0x411C34) */ int g_SavedGameFlags1;
    /* +0x1BC4 (0x411C38) */ int g_SavedGameFlags2;
    /* +0x1BC8 (0x411C3C) */ int g_SavedResourceID2;
    /* +0x1BCC (0x411C40) */ int g_PathTargetX;
    /* +0x1BD0 (0x411C44) */ int g_PathTargetY;
    /* +0x1BD4 (0x411C48) */ int g_PathStartX;
    /* +0x1BD8 (0x411C4C) */ int g_PathStartY;
    /* +0x1BDC (0x411C50) */ int g_PathDirection2;
    /* +0x1BE0 (0x411C54) */ int g_PathDirection1;
    /* +0x1BE4 (0x411C58) */ int g_BackbufferPixels;
    /* +0x1BE8 (0x411C5C) */ int g_BackbufferStride;
    /* +0x1BEC (0x411C60) */ int g_BackbufferHeight;
    /* +0x1BF0 (0x411C64) */ int g_CurrentScanlineWidth;
    /* +0x1BF4 (0x411C68) */ int g_hWaveOut;
    /* +0x1BF8 (0x411C6C) */ int g_WaveDeviceID;
    /* +0x1BFC (0x411C70) */ char pwh[256];
    /* +0x1CFC (0x411D70) */ int g_hMidiOut;
    /* +0x1D00 (0x411D74) */ int g_MidiDeviceID;
    /* +0x1D04 (0x411D78) */ int g_MidiTimerID;
    /* +0x1D08 (0x411D7C) */ int dword_411D7C;
    /* +0x1D0C (0x411D80) */ int g_MidiTicks;
    /* +0x1D10 (0x411D84) */ int g_MidiPlaying;
    /* +0x1D14 (0x411D88) */ int g_MidiLooping;
    /* +0x1D18 (0x411D8C) */ int g_MidiDataStart;
    /* +0x1D1C (0x411D90) */ int g_MidiDataPtr;
    /* +0x1D20 (0x411D94) */ char byte_411D94;
    /* +0x1D21 (0x411D95) */ char g_MidiVolume;
    /* +0x1D22          */ char _trail_g_MidiVolume[2];
    /* +0x1D24 (0x411D98) */ int g_TimerResolution;
    /* +0x1D28 (0x411D9C) */ int g_hGraphicsMemory;
    /* +0x1D2C (0x411DA0) */ int (__stdcall *g_pGraphicsFunc)();
    /* +0x1D30 (0x411DA4) */ int (__stdcall *g_pRegisterFunc)();
    /* +0x1D34 (0x411DA8) */ int (__stdcall *g_pUnregisterFunc)();
    /* +0x1D38 (0x411DAC) */ int g_hGraphicsDLL;
    /* +0x1D3C (0x411DB0) */ int g_GraphicsBuffers;
    /* +0x1D40 (0x411DB4) */ int dword_411DB4;
    /* +0x1D44 (0x411DB8) */ int dword_411DB8;
    /* +0x1D48 (0x411DBC) */ char byte_411DBC;
    /* +0x1D49 (0x411DBD) */ char byte_411DBD;
    /* +0x1D4A (0x411DBE) */ char byte_411DBE[114];
    /* +0x1DBC (0x411E30) */ int g_hMainWindow[4096];
    /* +0x5DBC (0x415E30) */ int g_GraphicsConfig;
    /* +0x5DC0 (0x415E34) */ int g_GraphicsState2;
    /* +0x5DC4 (0x415E38) */ int g_GraphicsState1;
    /* +0x5DC8 (0x415E3C) */ char g_ExecutablePath[64];
    /* +0x5E08 (0x415E7C) */ char g_VideoConfig[360];
    /* +0x5F70 (0x415FE4) */ int g_BitmapHandle;
    /* +0x5F74 (0x415FE8) */ int g_Reserved;
    /* +0x5F78 (0x415FEC) */ int g_MemoryDeviceContext;
    /* +0x5F7C (0x415FF0) */ int g_VideoWindowX;
    /* +0x5F80 (0x415FF4) */ int g_VideoWindowY;
    /* +0x5F84 (0x415FF8) */ int g_VideoWindowWidth;
    /* +0x5F88 (0x415FFC) */ int g_VideoWindowHeight;
    /* +0x5F8C (0x416000) */ char g_VideoFilePath[64];
    /* +0x5FCC (0x416040) */ int g_MCIDeviceID;
    /* +0x5FD0 (0x416044) */ int g_VideoWindowHandle;
    /* +0x5FD4 (0x416048) */ char g_VideoPlaying;
    /* +0x5FD5 (0x416049) */ char g_VideoExitRequested;
    /* +0x5FD6 (0x41604A) */ char g_VideoFlags[4];
    /* +0x5FDA (0x41604E) */ char g_VideoFlag3;
    /* +0x5FDB          */ char _trail_g_VideoFlag3[1];
    /* +0x5FDC (0x416050) */ int g_LastFrameTime;
    /* +0x5FE0          */ char _trail_g_LastFrameTime[268];
    /* +0x60EC (0x416160) */ int dword_416160;
    /* +0x60F0 (0x416164) */ int dword_416164;
    /* +0x60F4 (0x416168) */ int g_ScreenWidth;
    /* +0x60F8 (0x41616C) */ int g_ScreenHeight;
    /* +0x60FC (0x416170) */ int dword_416170;
    /* +0x6100 (0x416174) */ int dword_416174;
    /* +0x6104 (0x416178) */ int dword_416178;
    /* +0x6108 (0x41617C) */ int dword_41617C;
    /* +0x610C (0x416180) */ int dword_416180;
    /* +0x6110 (0x416184) */ int dword_416184;
    /* +0x6114 (0x416188) */ int dword_416188;
    /* +0x6118 (0x41618C) */ int dword_41618C;
    /* +0x611C (0x416190) */ int dword_416190;
    /* +0x6120 (0x416194) */ int g_GameFlags2;
    /* +0x6124 (0x416198) */ int g_GameFlags1;
    /* +0x6128 (0x41619C) */ int g_ResourceID2;
    /* +0x612C (0x4161A0) */ int g_CurrentTileX_Wrapped;
    /* +0x6130 (0x4161A4) */ int g_CurrentTileY_Wrapped;
    /* +0x6134 (0x4161A8) */ int g_PreviousTileX;
    /* +0x6138 (0x4161AC) */ int g_PreviousTileY;
    /* +0x613C (0x4161B0) */ MoveDirectionHandler g_TileProcessor;
    /* +0x6140 (0x4161B4) */ int (__stdcall *g_SpriteCommandHandler)(int);
    /* +0x6144 (0x4161B8) */ int g_SavedState;
    /* +0x6148 (0x4161BC) */ int g_ResourceID1;
    /* +0x614C (0x4161C0) */ RenderObject * g_RenderObjectsStart;
    /* +0x6150 (0x4161C4) */ RenderObject * g_RenderObjectsEnd;
    /* +0x6154 (0x4161C8) */ SpriteSlot * g_SpriteSlotArray;
    /* +0x6158 (0x4161CC) */ AnimationSlot * g_AnimationSlotArray;
    /* +0x615C (0x4161D0) */ int g_TileMapBuffer;
    /* +0x6160 (0x4161D4) */ int g_TileMapShift;
    /* +0x6164 (0x4161D8) */ SoundSlot * g_SoundSlotArray;
    /* +0x6168 (0x4161DC) */ FontSlot * g_FontSlotArray;
    /* +0x616C (0x4161E0) */ int g_ScreenPixelCount;
    /* +0x6170 (0x4161E4) */ int dword_4161E4;
    /* +0x6174 (0x4161E8) */ ScreenSnapshot * g_ScreenSnapshotArray;
    /* +0x6178 (0x4161EC) */ int g_SnapshotBasePtr;
    /* +0x617C (0x4161F0) */ int dword_4161F0;
    /* +0x6180 (0x4161F4) */ int dword_4161F4;
    /* +0x6184 (0x4161F8) */ int g_MaxCharCount;
    /* +0x6188 (0x4161FC) */ int dword_4161FC;
    /* +0x618C (0x416200) */ int dword_416200;
    /* +0x6190 (0x416204) */ int g_TileWidth;
    /* +0x6194 (0x416208) */ int g_TileHeight;
    /* +0x6198 (0x41620C) */ int video_queue_active;
    /* +0x619C          */ char _trail_video_queue_active[3];
    /* +0x619F (0x416213) */ char g_DefaultFrameRate;
    /* +0x61A0          */ char _trail_g_DefaultFrameRate[1];
    /* +0x61A1 (0x416215) */ char g_DisableCursor;
    /* +0x61A2 (0x416216) */ char g_DisplayMode[4];
    /* +0x61A6          */ char _trail_g_DisplayMode[110];
    /* +0x6214 (0x416288) */ char g_MemoryPool[16];
    /* +0x6224 (0x416298) */ OverlaySlot * g_OverlaySlotArray;
    /* +0x6228 (0x41629C) */ MusicTrackSlot * g_MusicTrackArray;
    /* +0x622C          */ char _trail_g_MusicTrackArray[8];
    /* +0x6234 (0x4162A8) */ int g_SavedScriptPtr;
    /* +0x6238 (0x4162AC) */ int g_snapshotIndex;
    /* +0x623C (0x4162B0) */ int dword_4162B0;
    /* +0x6240 (0x4162B4) */ char g_SoundEnabledFlag;
    /* +0x6241 (0x4162B5) */ char byte_4162B5;
    /* +0x6242 (0x4162B6) */ char g_ErrorFlag;
    /* +0x6243 (0x4162B7) */ char video_enabled_flag;
    /* +0x6244 (0x4162B8) */ int g_GraphicsConfigPtr;
    /* +0x6248 (0x4162BC) */ int g_SavedFrameRate;
    /* +0x624C (0x4162C0) */ int g_CurrentMusicIndex;
    /* +0x6250 (0x4162C4) */ int g_CurrentFontIndex;
    /* +0x6254 (0x4162C8) */ char byte_4162C8[12];
    /* +0x6260 (0x4162D4) */ int dword_4162D4;
    /* +0x6264 (0x4162D8) */ int g_CurrentSnapshotIndex;
    /* +0x6268 (0x4162DC) */ int g_SpecialMode;
    /* +0x626C (0x4162E0) */ GameLoopData * g_GameLoopDataPtr;
    /* +0x6270 (0x4162E4) */ int * g_CustomDataPtr1;
    /* +0x6274 (0x4162E8) */ int * g_CustomDataPtr2;
    /* +0x6278 (0x4162EC) */ int * g_CustomDataPtr3;
    /* +0x627C (0x4162F0) */ int g_TotalSnapshotCount;
    /* +0x6280 (0x4162F4) */ int dword_4162F4;
    /* +0x6284 (0x4162F8) */ char g_DataFilePath[64];
    /* +0x62C4 (0x416338) */ int dword_416338;
    /* +0x62C8 (0x41633C) */ int g_TileMapPtr;
    /* +0x62CC (0x416340) */ int g_MapMaxX;
    /* +0x62D0 (0x416344) */ int g_NegScreenWidth;
    /* +0x62D4 (0x416348) */ int g_MapMaxY;
    /* +0x62D8 (0x41634C) */ int g_GlobalVarsPtr;
    /* +0x62DC (0x416350) */ int g_CurrentObjectData;
    /* +0x62E0 (0x416354) */ int g_SpriteDirectionIndex;
    /* +0x62E4 (0x416358) */ int g_CurrentTileY;
    /* +0x62E8 (0x41635C) */ int g_CurrentTileX;
    /* +0x62EC (0x416360) */ int g_SelectedTileY;
    /* +0x62F0 (0x416364) */ int g_SelectedTileX;
    /* +0x62F4 (0x416368) */ int g_hAppInstance;
    /* +0x62F8 (0x41636C) */ int g_MainWindow;
    /* +0x62FC (0x416370) */ char dword_416370[5];
    /* +0x6301 (0x416375) */ char byte_416375[3];
    /* +0x6304 (0x416378) */ int dword_416378;
    /* +0x6308 (0x41637C) */ int dword_41637C;
    /* +0x630C (0x416380) */ short word_416380;
    /* +0x630E (0x416382) */ char word_416382[698];
    /* +0x65C8 (0x41663C) */ char g_hSemaphore[280];
    /* +0x66E0 (0x416754) */ int (*g_pfnSetEnvP)();
    /* +0x66E4 (0x416758) */ int dword_416758;
    /* +0x66E8 (0x41675C) */ short word_41675C;
    /* +0x66EA (0x41675E) */ char g_CurrentDirection;
    /* +0x66EB (0x41675F) */ char g_DemoMode;
    /* +0x66EC (0x416760) */ char g_RenderingInProgress;
    /* +0x66ED (0x416761) */ char g_FirstRun;
    /* +0x66EE (0x416762) */ int g_PreviousScreen;
    /* +0x66F2 (0x416766) */ char g_PreviousInput;
    /* +0x66F3 (0x416767) */ char g_ContinueRendering;
    /* +0x66F4 (0x416768) */ int video_recursion_counter;
    /* +0x66F8 (0x41676C) */ char g_RenderComplete;
    /* +0x66F9 (0x41676D) */ char g_CurrentInput;
    /* +0x66FA (0x41676E) */ char g_CurrentScreen;
    /* +0x66FB          */ char _trail_g_CurrentScreen[1];
    /* +0x66FC (0x416770) */ char g_GameStateFlag;
    /* +0x66FD (0x416771) */ char g_Buffer[15];
    /* Total: 26380 bytes (0x670C) */
};
#pragma pack(pop)

extern struct GameGlobals g_Globals;

/* ---- Field access macros ---- */
#define g_CursorObject (*(RenderObject*)g_Globals.g_CursorObject)
#define g_DirFlagRemap_Rotate90CCW g_Globals.g_DirFlagRemap_Rotate90CCW
#define g_DirFlagRemap_Rotate180 g_Globals.g_DirFlagRemap_Rotate180
#define g_DirFlagRemap_Rotate90CW g_Globals.g_DirFlagRemap_Rotate90CW
#define g_DirFlagRemap_FlipHorizontal g_Globals.g_DirFlagRemap_FlipHorizontal
#define g_DirFlagRemap_ReflectAntiDiag g_Globals.g_DirFlagRemap_ReflectAntiDiag
#define g_DirFlagRemap_FlipVertical g_Globals.g_DirFlagRemap_FlipVertical
#define g_DirFlagRemap_ReflectDiag g_Globals.g_DirFlagRemap_ReflectDiag
#define g_SpriteTransformTable g_Globals.g_SpriteTransformTable
#define g_TileMatchHandlers g_Globals.g_TileMatchHandlers
#define g_SpriteVariantTable_2A ((char*)&g_Globals.g_SpriteVariantTable_2A)
#define g_SpriteVariantTable_2B ((char*)&g_Globals.g_SpriteVariantTable_2B)
#define g_SpriteVariantTable_2C ((char*)&g_Globals.g_SpriteVariantTable_2C)
#define g_SpriteVariantTable_3A ((char*)&g_Globals.g_SpriteVariantTable_3A)
#define g_SpriteVariantTable_2D ((char*)&g_Globals.g_SpriteVariantTable_2D)
#define g_SpriteVariantTable_2E ((char*)&g_Globals.g_SpriteVariantTable_2E)
#define g_SpriteVariantTable_3B ((char*)&g_Globals.g_SpriteVariantTable_3B)
#define g_SpriteVariantTable_2F ((char*)&g_Globals.g_SpriteVariantTable_2F)
#define g_SpriteVariantTable_3C ((char*)&g_Globals.g_SpriteVariantTable_3C)
#define g_SpriteVariantTable_3D ((char*)&g_Globals.g_SpriteVariantTable_3D)
#define g_SpriteVariantTable_4A ((char*)&g_Globals.g_SpriteVariantTable_4A)
#define g_MoveDirectionHandlers g_Globals.g_MoveDirectionHandlers
#define g_RandomSeed g_Globals.g_RandomSeed
#define aInsufficientMe g_Globals.aInsufficientMe
#define aInvalidGameDat g_Globals.aInvalidGameDat
#define dword_41020C ((int*)g_Globals.dword_41020C)
#define dword_41022C g_Globals.dword_41022C
#define dword_410230 g_Globals.dword_410230
#define dword_410234 g_Globals.dword_410234
#define dword_410238 ((int*)g_Globals.dword_410238)
#define byte_410298 g_Globals.byte_410298
#define aMoviePlaybackE g_Globals.aMoviePlaybackE
#define g_NativeFuncTable g_Globals.g_NativeFuncTable
#define g_MirrorDirectionTable g_Globals.g_MirrorDirectionTable
#define Format g_Globals.g_Format
#define funcs_409620 g_Globals.funcs_409620
#define g_pfnWriteWaveBuffer g_Globals.g_pfnWriteWaveBuffer
#define g_pfnStartMidiPlayback g_Globals.g_pfnStartMidiPlayback
#define g_pfnResetWave g_Globals.g_pfnResetWave
#define g_pfnStopMidiPlayback g_Globals.g_pfnStopMidiPlayback
#define g_pfnGetWaveVolume g_Globals.g_pfnGetWaveVolume
#define g_pfnGetMidiVolume g_Globals.g_pfnGetMidiVolume
#define g_pfnGetNextWaveBuffer g_Globals.g_pfnGetNextWaveBuffer
#define g_pfnPauseWave g_Globals.g_pfnPauseWave
#define g_pfnResumeWave g_Globals.g_pfnResumeWave
#define g_pfnSetWaveVolume g_Globals.g_pfnSetWaveVolume
#define g_pfnSetMidiVolume g_Globals.g_pfnSetMidiVolume
#define g_pfnCleanupMultimedia g_Globals.g_pfnCleanupMultimedia
#define aGmwDll g_Globals.aGmwDll
#define aUtunregister g_Globals.aUtunregister
#define ProcName g_Globals.ProcName
#define LibFileName g_Globals.LibFileName
#define bmi (*(BITMAPINFO*)g_Globals.g_bmi)
#define aGameMakerPlaye g_Globals.aGameMakerPlaye
#define aHlp g_Globals.aHlp
#define RootPathName g_Globals.RootPathName
#define aBmp g_Globals.aBmp
#define aAvi g_Globals.aAvi
#define asc_410892 g_Globals.asc_410892
#define aInvalidMovieBa g_Globals.aInvalidMovieBa
#define aIntro g_Globals.aIntro
#define aGameRequiresLa g_Globals.aGameRequiresLa
#define ClassName g_Globals.ClassName
#define ModuleName g_Globals.ModuleName
#define aCreatedibsecti g_Globals.aCreatedibsecti
#define xmmword_4109D4 g_Globals.xmmword_4109D4
#define aSDS g_Globals.aSDS
#define SubStr g_Globals.g_SubStr
#define aSS g_Globals.aSS
#define aA g_Globals.aA
#define g_MouseX g_Globals.g_MouseX
#define g_MouseY g_Globals.g_MouseY
#define g_CameraOffsetX g_Globals.g_CameraOffsetX
#define g_CameraOffsetY g_Globals.g_CameraOffsetY
#define g_DirtyRegionsList g_Globals.g_DirtyRegionsList
#define g_LastCheckedRenderObject g_Globals.g_LastCheckedRenderObject
#define g_JumpBuffer g_Globals.g_jmpbuf
#define g_TileMapModified g_Globals.g_TileMapModified
#define g_InputState g_Globals.g_InputState
#define g_RandomChoiceArray ((short*)g_Globals.g_RandomChoiceArray)
#define g_MemoryPoolStart g_Globals.g_MemoryPoolStart
#define g_MemoryPoolCurrent g_Globals.g_MemoryPoolCurrent
#define g_MemoryPoolAvailable g_Globals.g_MemoryPoolAvailable
#define dword_4115C8 g_Globals.dword_4115C8
#define g_BufferSize g_Globals.g_BufferSize
#define g_FileBufferSize g_Globals.g_FileBufferSize
#define g_BufferPtr g_Globals.g_BufferPtr
#define g_DataOffset g_Globals.g_DataOffset
#define g_IndexTableOffset g_Globals.g_IndexTableOffset
#define g_MaxResourceIndex g_Globals.g_MaxResourceIndex
#define g_TemplateDataSize g_Globals.g_TemplateDataSize
#define g_DecompressedDataSize g_Globals.g_DecompressedDataSize
#define g_CurrentOpcode g_Globals.g_CurrentOpcode
#define g_TemplateDataBuffer g_Globals.g_TemplateDataBuffer
#define opcodeDataPtr g_Globals.g_opcodeDataPtr
#define g_CurrentScenePtr g_Globals.g_CurrentScenePtr
#define g_ActiveSnapshotIndex g_Globals.g_ActiveSnapshotIndex
#define byte_411698 g_Globals.byte_411698
#define g_FontRenderFlags g_Globals.g_FontRenderFlags
#define g_CachedSpriteOffset g_Globals.g_CachedSpriteOffset
#define g_MaxDeferredLoadSize g_Globals.g_MaxDeferredLoadSize
#define g_SpriteDataBuffer g_Globals.g_SpriteDataBuffer
#define offset g_Globals.g_fileOffset
#define video_command_type g_Globals.video_command_type
#define video_chunk_type g_Globals.video_chunk_type
#define has_low_dword g_Globals.has_low_dword
#define has_high_dword g_Globals.has_high_dword
#define chunk_data_qword g_Globals.chunk_data_qword
#define video_repeat_count g_Globals.video_repeat_count
#define video_file_offset g_Globals.video_file_offset
#define target_frame_delay g_Globals.target_frame_delay
#define compressed_buffer_size g_Globals.compressed_buffer_size
#define compressed_buffer g_Globals.compressed_buffer
#define frame_data_size g_Globals.frame_data_size
#define frame_data_buffer g_Globals.frame_data_buffer
#define palette_size g_Globals.palette_size
#define palette_buffer g_Globals.palette_buffer
#define sound_data_size g_Globals.sound_data_size
#define sound_data_buffer g_Globals.sound_data_buffer
#define music_data_size g_Globals.music_data_size
#define music_data_buffer g_Globals.music_data_buffer
#define sound_playing_flag g_Globals.sound_playing_flag
#define music_playing_flag g_Globals.music_playing_flag
#define video_paused_flag g_Globals.video_paused_flag
#define frame_x_offset g_Globals.frame_x_offset
#define frame_y_offset g_Globals.frame_y_offset
#define frame_width g_Globals.frame_width
#define frame_height g_Globals.frame_height
#define frame_ready_flag g_Globals.frame_ready_flag
#define last_frame_time g_Globals.last_frame_time
#define frame_counter g_Globals.frame_counter
#define skip_frame_counter g_Globals.skip_frame_counter
#define byte_411710 g_Globals.byte_411710
#define g_TextCommandPtr g_Globals.g_TextCommandPtr
#define g_TextFontIndex g_Globals.g_TextFontIndex
#define g_TextRenderX g_Globals.g_TextRenderX
#define g_TextRenderY g_Globals.g_TextRenderY
#define g_TextCharRangePtr g_Globals.g_TextCharRangePtr
#define g_TextInputBuffer g_Globals.g_TextInputBuffer
#define g_TextCharacterObjects g_Globals.g_TextCharacterObjects
#define g_TextInputLength g_Globals.g_TextInputLength
#define g_TextInputMaxLength g_Globals.g_TextInputMaxLength
#define g_TextInputTargetPtr g_Globals.g_TextInputTargetPtr
#define g_TextInputMode g_Globals.g_TextInputMode
#define g_TextInputActive g_Globals.g_TextInputActive
#define g_TextInputNumericMode g_Globals.g_TextInputNumericMode
#define g_SavedGameFlags1 g_Globals.g_SavedGameFlags1
#define g_SavedGameFlags2 g_Globals.g_SavedGameFlags2
#define g_SavedResourceID2 g_Globals.g_SavedResourceID2
#define g_PathTargetX g_Globals.g_PathTargetX
#define g_PathTargetY g_Globals.g_PathTargetY
#define g_PathStartX g_Globals.g_PathStartX
#define g_PathStartY g_Globals.g_PathStartY
#define g_PathDirection2 g_Globals.g_PathDirection2
#define g_PathDirection1 g_Globals.g_PathDirection1
#define g_BackbufferPixels g_Globals.g_BackbufferPixels
#define g_BackbufferStride g_Globals.g_BackbufferStride
#define g_BackbufferHeight g_Globals.g_BackbufferHeight
#define g_CurrentScanlineWidth g_Globals.g_CurrentScanlineWidth
#define g_hWaveOut g_Globals.g_hWaveOut
#define g_WaveDeviceID g_Globals.g_WaveDeviceID
#define pwh (*(WAVEHDR*)g_Globals.pwh)
#define g_hMidiOut g_Globals.g_hMidiOut
#define g_MidiDeviceID g_Globals.g_MidiDeviceID
#define g_MidiTimerID g_Globals.g_MidiTimerID
#define dword_411D7C g_Globals.dword_411D7C
#define g_MidiTicks g_Globals.g_MidiTicks
#define g_MidiPlaying g_Globals.g_MidiPlaying
#define g_MidiLooping g_Globals.g_MidiLooping
#define g_MidiDataStart g_Globals.g_MidiDataStart
#define g_MidiDataPtr g_Globals.g_MidiDataPtr
#define byte_411D94 g_Globals.byte_411D94
#define g_MidiVolume g_Globals.g_MidiVolume
#define g_TimerResolution g_Globals.g_TimerResolution
#define g_hGraphicsMemory g_Globals.g_hGraphicsMemory
#define g_pGraphicsFunc g_Globals.g_pGraphicsFunc
#define g_pRegisterFunc g_Globals.g_pRegisterFunc
#define g_pUnregisterFunc g_Globals.g_pUnregisterFunc
#define g_hGraphicsDLL g_Globals.g_hGraphicsDLL
#define g_GraphicsBuffers ((int*)&g_Globals.g_GraphicsBuffers)
#define dword_411DB4 ((int*)&g_Globals.dword_411DB4)
#define dword_411DB8 ((int*)&g_Globals.dword_411DB8)
#define byte_411DBC ((char*)&g_Globals.byte_411DBC)
#define byte_411DBD ((char*)&g_Globals.byte_411DBD)
#define byte_411DBE ((char*)&g_Globals.byte_411DBE)
#define g_hMainWindow g_Globals.g_hMainWindow
#define g_GraphicsConfig g_Globals.g_GraphicsConfig
#define g_GraphicsState2 g_Globals.g_GraphicsState2
#define g_GraphicsState1 g_Globals.g_GraphicsState1
#define g_ExecutablePath g_Globals.g_ExecutablePath
#define g_VideoConfig (*(VideoConfig*)g_Globals.g_VideoConfig)
#define g_BitmapHandle g_Globals.g_BitmapHandle
#define g_Reserved g_Globals.g_Reserved
#define g_MemoryDeviceContext g_Globals.g_MemoryDeviceContext
#define g_VideoWindowX g_Globals.g_VideoWindowX
#define g_VideoWindowY g_Globals.g_VideoWindowY
#define g_VideoWindowWidth g_Globals.g_VideoWindowWidth
#define g_VideoWindowHeight g_Globals.g_VideoWindowHeight
#define g_VideoFilePath g_Globals.g_VideoFilePath
#define g_MCIDeviceID g_Globals.g_MCIDeviceID
#define g_VideoWindowHandle g_Globals.g_VideoWindowHandle
#define g_VideoPlaying g_Globals.g_VideoPlaying
#define g_VideoExitRequested g_Globals.g_VideoExitRequested
#define g_VideoFlags g_Globals.g_VideoFlags
#define g_VideoFlag3 g_Globals.g_VideoFlag3
#define g_LastFrameTime g_Globals.g_LastFrameTime
#define dword_416160 g_Globals.dword_416160
#define dword_416164 g_Globals.dword_416164
#define g_ScreenWidth g_Globals.g_ScreenWidth
#define g_ScreenHeight g_Globals.g_ScreenHeight
#define dword_416170 g_Globals.dword_416170
#define dword_416174 g_Globals.dword_416174
#define dword_416178 g_Globals.dword_416178
#define dword_41617C g_Globals.dword_41617C
#define dword_416180 g_Globals.dword_416180
#define dword_416184 g_Globals.dword_416184
#define dword_416188 g_Globals.dword_416188
#define dword_41618C g_Globals.dword_41618C
#define dword_416190 g_Globals.dword_416190
#define g_GameFlags2 g_Globals.g_GameFlags2
#define g_GameFlags1 g_Globals.g_GameFlags1
#define g_ResourceID2 g_Globals.g_ResourceID2
#define g_CurrentTileX_Wrapped g_Globals.g_CurrentTileX_Wrapped
#define g_CurrentTileY_Wrapped g_Globals.g_CurrentTileY_Wrapped
#define g_PreviousTileX g_Globals.g_PreviousTileX
#define g_PreviousTileY g_Globals.g_PreviousTileY
#define g_TileProcessor g_Globals.g_TileProcessor
#define g_SpriteCommandHandler g_Globals.g_SpriteCommandHandler
#define g_SavedState g_Globals.g_SavedState
#define g_ResourceID1 g_Globals.g_ResourceID1
#define g_RenderObjectsStart g_Globals.g_RenderObjectsStart
#define g_RenderObjectsEnd g_Globals.g_RenderObjectsEnd
#define g_SpriteSlotArray g_Globals.g_SpriteSlotArray
#define g_AnimationSlotArray g_Globals.g_AnimationSlotArray
#define g_TileMapBuffer g_Globals.g_TileMapBuffer
#define g_TileMapShift g_Globals.g_TileMapShift
#define g_SoundSlotArray g_Globals.g_SoundSlotArray
#define g_FontSlotArray g_Globals.g_FontSlotArray
#define g_ScreenPixelCount g_Globals.g_ScreenPixelCount
#define dword_4161E4 g_Globals.dword_4161E4
#define g_ScreenSnapshotArray g_Globals.g_ScreenSnapshotArray
#define g_SnapshotBasePtr g_Globals.g_SnapshotBasePtr
#define dword_4161F0 g_Globals.dword_4161F0
#define dword_4161F4 g_Globals.dword_4161F4
#define MaxCharCount g_Globals.g_MaxCharCount
#define dword_4161FC g_Globals.dword_4161FC
#define dword_416200 g_Globals.dword_416200
#define g_TileWidth g_Globals.g_TileWidth
#define g_TileHeight g_Globals.g_TileHeight
#define video_queue_active g_Globals.video_queue_active
#define g_DefaultFrameRate g_Globals.g_DefaultFrameRate
#define g_DisableCursor g_Globals.g_DisableCursor
#define g_DisplayMode g_Globals.g_DisplayMode
#define g_MemoryPool (*(MemoryPoolDescriptor*)g_Globals.g_MemoryPool)
#define g_OverlaySlotArray g_Globals.g_OverlaySlotArray
#define g_MusicTrackArray g_Globals.g_MusicTrackArray
#define g_SavedScriptPtr g_Globals.g_SavedScriptPtr
#define snapshotIndex g_Globals.g_snapshotIndex
#define dword_4162B0 g_Globals.dword_4162B0
#define g_SoundEnabledFlag g_Globals.g_SoundEnabledFlag
#define byte_4162B5 g_Globals.byte_4162B5
#define g_ErrorFlag g_Globals.g_ErrorFlag
#define video_enabled_flag g_Globals.video_enabled_flag
#define g_GraphicsConfigPtr g_Globals.g_GraphicsConfigPtr
#define g_SavedFrameRate g_Globals.g_SavedFrameRate
#define g_CurrentMusicIndex g_Globals.g_CurrentMusicIndex
#define g_CurrentFontIndex g_Globals.g_CurrentFontIndex
#define byte_4162C8 g_Globals.byte_4162C8
#define dword_4162D4 g_Globals.dword_4162D4
#define g_CurrentSnapshotIndex g_Globals.g_CurrentSnapshotIndex
#define g_SpecialMode g_Globals.g_SpecialMode
#define g_GameLoopDataPtr g_Globals.g_GameLoopDataPtr
#define g_CustomDataPtr1 g_Globals.g_CustomDataPtr1
#define g_CustomDataPtr2 g_Globals.g_CustomDataPtr2
#define g_CustomDataPtr3 g_Globals.g_CustomDataPtr3
#define g_TotalSnapshotCount g_Globals.g_TotalSnapshotCount
#define dword_4162F4 g_Globals.dword_4162F4
#define g_DataFilePath g_Globals.g_DataFilePath
#define dword_416338 g_Globals.dword_416338
#define g_TileMapPtr g_Globals.g_TileMapPtr
#define g_MapMaxX g_Globals.g_MapMaxX
#define g_NegScreenWidth g_Globals.g_NegScreenWidth
#define g_MapMaxY g_Globals.g_MapMaxY
#define g_GlobalVarsPtr g_Globals.g_GlobalVarsPtr
#define g_CurrentObjectData g_Globals.g_CurrentObjectData
#define g_SpriteDirectionIndex g_Globals.g_SpriteDirectionIndex
#define g_CurrentTileY g_Globals.g_CurrentTileY
#define g_CurrentTileX g_Globals.g_CurrentTileX
#define g_SelectedTileY g_Globals.g_SelectedTileY
#define g_SelectedTileX g_Globals.g_SelectedTileX
#define g_hAppInstance g_Globals.g_hAppInstance
#define g_MainWindow g_Globals.g_MainWindow
#define dword_416370 g_Globals.dword_416370
#define byte_416375 g_Globals.byte_416375
#define dword_416378 g_Globals.dword_416378
#define dword_41637C g_Globals.dword_41637C
#define word_416380 g_Globals.word_416380
#define word_416382 g_Globals.word_416382
#define hSemaphore g_Globals.g_hSemaphore
#define g_pfnSetEnvP g_Globals.g_pfnSetEnvP
#define dword_416758 g_Globals.dword_416758
#define word_41675C g_Globals.word_41675C
#define g_CurrentDirection g_Globals.g_CurrentDirection
#define g_DemoMode g_Globals.g_DemoMode
#define g_RenderingInProgress g_Globals.g_RenderingInProgress
#define g_FirstRun g_Globals.g_FirstRun
#define g_PreviousScreen g_Globals.g_PreviousScreen
#define g_PreviousInput g_Globals.g_PreviousInput
#define g_ContinueRendering g_Globals.g_ContinueRendering
#define video_recursion_counter g_Globals.video_recursion_counter
#define g_RenderComplete g_Globals.g_RenderComplete
#define g_CurrentInput g_Globals.g_CurrentInput
#define g_CurrentScreen g_Globals.g_CurrentScreen
#define g_GameStateFlag g_Globals.g_GameStateFlag

