#ifndef PILOTS_FWD_H
#define PILOTS_FWD_H

#pragma once

#define WINDOWS_IGNORE_PACKING_MISMATCH

#include <windows.h>
#include <mmsystem.h>
#include <io.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <time.h>
#include <setjmp.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <vfw.h>

#include "defs.h"
#include "pilots_types.h"
#include "debug_log.h"

/* Blit function pointer type (for dispatch - 5 args) */
typedef unsigned char *(__cdecl *BlitFuncPtrInternal)(int, int, int, unsigned char *, unsigned char *);

/* Forward declarations for blit functions */
unsigned char *__cdecl BlitAdditive_Raw(int width, int height,
    int strideAdjust, unsigned char *dst, unsigned char *src);
char *__cdecl RLEBlitAdditive_TypeA(int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);
char *__cdecl RLEBlitAdditive_TypeB(int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);
char *__cdecl RLEBlitAdditive_TypeC(int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);

/* ---- Single packed global block ----
   All game globals placed in one contiguous #pragma pack(push, 1) struct,
   matching the original PILOTS.EXE data section layout byte-for-byte.
   Generated by gen_globals.py from IDA data export. */

#include "game_globals_struct.h"

/* Backward-compatible aliases for old SpriteConfigBlock field names */
#define g_MaxReadBufferSize MaxCharCount
#define g_snapshotIndex snapshotIndex
/* unk_4162A0 = original addr 0x4162A0 = g_MusicTrackArray(0x41629C) + 4 */
#define unk_4162A0 g_Globals._trail_g_MusicTrackArray

#include "pilots_globals.h"

#endif /* PILOTS_FWD_H */
