#ifndef PILOTS_GLOBALS_H
#define PILOTS_GLOBALS_H

#pragma once

/* Extern global variable declarations (defined in globals.c) */

extern char g_SaveMagic1[8];
extern char g_SaveMagic2[4];
extern BlitFuncPtrInternal g_BlitFuncTable[4];
extern int g_DissolvePatternX[16];
extern int g_DissolvePatternY[16];
extern STARTUPINFOA g_StartupInfoTemplate;
extern PROCESS_INFORMATION g_ProcessInfoTemplate;
extern char g_SmallTempBuffer[152];

/* Null stub functions */
void __stdcall nullsub_3(int a1);
int nullsub_4(void);
int nullsub_5(void);
_DWORD nullsub_6(void);
void __stdcall TransformDir_Identity(SpriteDesc *desc);

/* Function prototypes */
int __stdcall AddDirtyRegion(int a1, int a2, int a3, int a4);
int __stdcall AddObjectToDirtyRegionByIndex(int a1);
int __stdcall AddObjectToDirtyRegions(RenderObject *object);
unsigned int *__stdcall AllocFromMemoryPool(unsigned int a1);
int __stdcall AllocMemoryChunk(unsigned int a1);
unsigned int *AllocOpcodeBuffer();
RenderObject *AllocRenderObject();
char *__stdcall AllocTempBuffer(unsigned int size);
BOOL AlwaysTrue();
int __stdcall BlendPixelBuffersSaturated(unsigned int a1, int *a2, int *a3);
unsigned char *__cdecl BlitAdditive_Raw( int width, int height, int strideAdjust, unsigned char *dst, unsigned char *src);
int __stdcall BlitDirtyRegion(char a1, int a2, int a3, int y, int x);
int __stdcall BlitRectToScreen(int bmp_height, int cy, int cx, int y, int x, void *lpBits);
char __stdcall BlitScreenWithDissolve( char use_dissolve, int bmp_height, int unused, int rect_height, int rect_width, int rect_y, int rect_x, void *lpBits);
int __stdcall BufferedRead(unsigned int maxBytes, char *DstBuf);
int __stdcall BuildAlternateSavePath(char *Str, LPSTR a2);
int __stdcall BuildSaveFilePath(int a1, const char *a2, char *Source, LPSTR a4);
int BuildWalkMapAllPassable();
int __stdcall BuildWalkMapByTileType(unsigned __int8 a1);
int __stdcall BuildWalkMapDirect(unsigned __int8 *bitmask);
int __stdcall BuildWalkMapDirectByType(unsigned __int8 a1);
int __stdcall BuildWalkMapInverted(unsigned __int8 *bitmask);
int __stdcall BuildWalkMapObstaclesByType(unsigned __int8 a1);
int __stdcall BuildWalkMapWithObstacles(unsigned __int8 *bitmask);
int __stdcall CalculateObjectPosition(RenderObject *object);
int __stdcall CaptureScreenSnapshot(int snapIdx);
int __stdcall CheckAnimationFrameAvailable(int a1);
BOOL CheckGameState();
char __stdcall CheckMCIError(MCIERROR mcierr);
int __stdcall CheckObjectHitTest(int y, int x, RenderObject *object);
BOOL __stdcall CheckRotatedDirectionMatch(int base_direction, int expected_direction);
int __stdcall CheckSaveFileExists(int a1);
BOOL __stdcall CheckVideoFileExists(char *Str, char *a2, char *lpFileName);
int *CleanupGameLoop();
int CleanupGameResources();
int CleanupGameState();
BOOL CleanupHelpAndWindow();
MMRESULT CleanupMidiOut();
int CleanupMultimedia();
char CleanupVideoResources();
MMRESULT CleanupWaveOut();
void __stdcall ClearBackbuffer(unsigned __int8 colorIndex);
void *__stdcall ClearBuffer(size_t Size, void *buffer);
void *__stdcall ClearCustomSaveRegions(_DWORD *data_desc);
int __stdcall ClearDirtyRegionsAndInit(char a1);
void __cdecl ClearInputAndShutdownAudio();
char ClearInputBuffer();
void ClearRenderAndMemoryPoolState();
int CloseFile();
int CloseFile_Wrapper();
int CloseSaveFile();
int __cdecl ComputeDirectDirection();
void __stdcall CopyAudioBufferAndPadSilence(unsigned int byteSize, const void *srcBuffer, void *dstBuffer);
void __stdcall CopyRectToBackbuffer( int bottom, int right, int top, int left, int srcStride, int srcWidth, int offsetY, int offsetX, void *srcPtr);
int __stdcall CreateFontRenderObject(char is_overlay, unsigned __int16 posY, unsigned __int16 posX, int font_index);
char *__stdcall CreateHelpFilePath(char *Source);
HDC __stdcall CreateMainWindow(struct VideoConfigEx *config);
__int16 __stdcall CreateTileObject(int a1, int a2, __int16 a3);
char __stdcall DecodeVLQ(char *resultBuffer);
int __stdcall DeleteSaveFile(int save_slot, int ext_string, char *base_path);
int __stdcall DeleteTextCharacters(int char_count);
int DisplayErrorMessage();
char __stdcall DrawSpriteFlippedH(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __stdcall DrawSpriteFlippedHV(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __stdcall DrawSpriteFlippedV(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __stdcall DrawSpriteTransparent(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
int Error_InsufficientMemory();
int __stdcall EvaluateScriptBytecode(unsigned __int64 accumulator, BYTE *bytecode);
char __stdcall ExecuteGameLoop(char skipCapture, int snapIdx);
int __stdcall ExecuteScriptWithContext( char direction, unsigned __int8 tile_y, unsigned __int8 tile_x, int object_data, int resource_id, int game_flags1, int game_flags2, BYTE *script_ptr);
int __stdcall ExecuteVideoPlayback(int videoIndex);
char __cdecl ExpandWave_Pass1();
char __cdecl ExpandWave_Pass2();
char __cdecl ExpandWave_Pass3();
int FileTell();
char __stdcall FindDriveByType(char drive_type, _BYTE *drive_type_map, _BYTE *out_drive_path);
FontSlot *__stdcall FindFontSlotByPointer(int a1);
int __stdcall FindPathToTarget(char use_direct_direction);
BOOL __stdcall FindVideoOnRemovableDrives(_BYTE *a1, _BYTE *a2);
int __stdcall FixupObjectPointers(int base_adjust, int object_count, char *object_data);
BOOL FlushGDI(void);
int *__stdcall FreeMemoryBlock(int a1);
int __stdcall FreeRenderObject(RenderObject *a1);
BOOL __stdcall GameMainLoop(int opcodeType, int startResourceId);
char __stdcall GameOpcodeDispatcher( int opcodeData, int dataOffset, int arrayIdx, int subIdx, int slotIdx, int opcodeType);
void GameState_Reset();
HFILE __stdcall Game_OpenFile(LPCSTR lpFileName, LPOFSTRUCT lpReOpenBuff, UINT uStyle);
size_t GetCurrentFileOffset();
int GetCurrentScreenMode();
HCURSOR GetGameCursor();
int GetMaxScreenMode();
int __stdcall GetMidiVolume(DWORD a1);
unsigned int GetNextWaveBuffer();
int __stdcall GetWaveVolume(DWORD a1);
char __stdcall HandleGameEvent(int coordY, int coordX);
BOOL __stdcall HandleHelpRequest(DWORD *pHelpContext);
int HandleVideoError();
int HideTextInput();
char __stdcall InitBackbuffer(int videoConfig, VideoDataBuffer *dataBuffer);
char __stdcall InitDirectDraw_Win95(DWORD_PTR *pHwnd);
char InitDisplay();
void *__stdcall InitFileReadBuffer(void *buffer);
BOOL __stdcall InitGameState(int gameOpcode);
char __stdcall InitGraphics(_BYTE *pMaxScreen, _BYTE *pCurrentScreen, int unused, unsigned __int8 graphicsConfig);
char __stdcall InitGraphicsMode(int updateDirtyRegions, int fontIndex);
char __stdcall InitGraphics_WinNT(int a1);
int InitMidiOut();
int InitRenderingEngine();
void *__stdcall InitSlotFromTemplate(void *a1);
int __stdcall InitWaveOut(DWORD_PTR *a1);
void *InitializeFrameBuffers();
BOOL __stdcall InitializeGame(int gameOpcode, char *dataFilePath);
BOOL __stdcall InitializeVideoPlayer(int Offset);
BOOL __stdcall InitializeVideoSystem(void *a1, struct VideoConfigEx *a2, struct VideoDataBuffer *a3);
char __stdcall LZSSDecompress(int a1, _BYTE *a2, char *a3);
BOOL __stdcall LaunchProcessAndWait(LPSTR lpCommandLine);
char __stdcall LoadDataFile(char *FileName);
int __stdcall LoadGameFromFile(int save_slot);
char __stdcall LoadResourceById(unsigned int resourceId);
unsigned __int16 *__stdcall LoadSpriteData(unsigned __int16 *a1);
int __stdcall LoadVideoBitmap(char *FileName);
__declspec(noreturn) void LongjmpRestart();
LRESULT __stdcall MainWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
void __stdcall MidiTimerCallback(UINT uTimerID, UINT uMsg, DWORD_PTR dwUser, DWORD_PTR dw1, DWORD_PTR dw2);
unsigned __int8 MixAudioBuffers();
char __stdcall MoveObjectOnTileMap(int a1);
char __cdecl MultimediaStub_NoArgs();
char __stdcall MultimediaStub_OneArg(int param);
char __stdcall MultimediaStub_StartMidi(int param);
int Native_CalcLayerFromHeight();
BOOL __stdcall Native_CheckCurrentFontSlot(int a1);
int __stdcall Native_CheckDirectionMatch(char a1);
BOOL __stdcall Native_CheckInputFlags(int a1);
BOOL __stdcall Native_CheckInputKey2Exact(int a1);
BOOL __stdcall Native_CheckInputKey2Match(int a1);
BOOL __stdcall Native_CheckInputKeyExact(int a1);
BOOL __stdcall Native_CheckInputKeyMatch(int a1);
BOOL __stdcall Native_CheckRenderLayer(int a1);
BOOL __stdcall Native_CheckScreenId(int a1);
BOOL __stdcall Native_CheckStateFlags(int a1);
int __stdcall Native_CheckVideoCounter(_BYTE *a1);
int Native_ClearSpecialMode();
char *__stdcall Native_CopyString(char *Source, char *Destination);
int __stdcall Native_CreateTileAction(int a1);
int __stdcall Native_CreateTileObject(char a1);
int __stdcall Native_CreateTileObjectMirrored(char a1);
int Native_EnableContinueRendering();
int __stdcall Native_ExecuteCommand(LPSTR lpCommandLine);
int __stdcall Native_FadeEffect(int a1, unsigned __int8 a2);
unsigned int __stdcall Native_GetRandom(int a1);
int __stdcall Native_GetRenderLayer(_BYTE *a1);
BOOL __fastcall Native_GetSystemFlag(char a1, int a2, int a3);
int Native_InitGraphicsDefault();
int __stdcall Native_InitGraphicsWithFont(int fontIndex);
BOOL Native_IsClickModeActive();
BOOL Native_IsInputModeActive();
BOOL Native_IsOverlaySlotEmpty();
BOOL Native_IsScreenTransition();
int __stdcall Native_MeasureTextAtTile(int a1, int a2);
int __stdcall Native_PlayVideo(char *videoPath);
int __stdcall Native_RandomizeAnimSlot0(int a1);
int __stdcall Native_RandomizeAnimSlot1(int a1);
int Native_RemoveOverlayObject();
int __stdcall Native_RenderAtCurrentTile(int a1);
int Native_ResetInputState();
__declspec(noreturn) void __stdcall Native_RestoreGameSnapshot(int snapIdx);
int __stdcall Native_SetPaletteEntry(int a1, _BYTE *a2);
int __stdcall Native_SetRenderLayer(char a1);
int __stdcall Native_SetSystemFlag(int a1);
int __stdcall Native_SetTimerCallback(ULONG_PTR dwData);
BOOL __stdcall Native_TestGameFlag(char a1);
int __stdcall Native_TransitionEffect(int a1);
int __stdcall Native_TransitionEffectEx(int a1, char a2);
char OpenMCIVideoDevice();
unsigned int __stdcall OpenSaveFile(int save_slot, int ext_string, char *base_path);
char ParseVideoHeader();
int __stdcall PathfindByTileType(unsigned __int8 pathfind_mode, char tile_type, unsigned __int8 search_type);
int __stdcall PathfindWithBitmask(unsigned __int8 pathfind_mode, unsigned __int8 anim_index, char search_type);
BOOL PauseWave();
char __cdecl PauseWavePlayback();
char __stdcall PlayIntroVideo(int windowHeight, int windowWidth, int windowY, int windowX, char *videoPath);
int PlayMCIVideo();
int __stdcall PlayMusicTrack(int a1);
char __stdcall PlaySoundEffect(char a1, char a2, char a3, int *a4);
char PlayVideoMusic();
int PlayVideoSoundEffect();
int __stdcall PrepareTextDisplay(int a1);
int __stdcall ProcessAbsoluteTileCoords(int a1);
char ProcessAnimationFrame();
BOOL __stdcall ProcessGameFrame( char inputState, unsigned __int8 inputCode, char inputFlag, unsigned __int8 eventCode, int coordY, int coordX, int altCoordY, int altCoordX, int mouseY, int mouseX);
int __stdcall ProcessInputAndRender( char inputFlag, unsigned __int8 eventCode, int coordY, int coordX, int altCoordY, int altCoordX);
BOOL ProcessMessages();
MMRESULT ProcessMidiEvents();
char ProcessNormalEvent();
int __stdcall ProcessOverlayText(int a1, int a2);
BOOL __stdcall ProcessRelativeTileCoords(int a1);
char __stdcall ProcessSpecialEvent(char keyCode);
char ProcessSpriteData();
char __stdcall ProcessTextInput(unsigned __int8 keyCode);
char __stdcall ProcessVideoCommands(int Offset);
char __stdcall PumpWindowMessages(DWORD *timestamp);
unsigned __int8 *__stdcall RLEBlitAdditive_Dispatch(int a1, int a2, int a3, int a4, int a5, unsigned __int8 *a6);
char *__cdecl RLEBlitAdditive_TypeA( int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);
char *__cdecl RLEBlitAdditive_TypeB( int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);
char *__cdecl RLEBlitAdditive_TypeC( int a1, int a2, int a3, int a4, _BYTE *a5, char *a6);
int __stdcall RandomSpriteAttrib_2A(int a1);
int __stdcall RandomSpriteAttrib_2B(int a1);
int __stdcall RandomSpriteAttrib_2C(int a1);
int __stdcall RandomSpriteAttrib_2D(int a1);
int __stdcall RandomSpriteAttrib_2E(int a1);
int __stdcall RandomSpriteAttrib_2F(int a1);
int __stdcall RandomSpriteAttrib_3A(int renderObj);
int __stdcall RandomSpriteAttrib_3B(int a1);
int __stdcall RandomSpriteAttrib_3C(int a1);
int __stdcall RandomSpriteAttrib_3D(int a1);
int __stdcall RandomSpriteAttrib_4A(int a1);
int __stdcall RandomSpriteAttrib_Clear(int a1);
int __stdcall ReadAndDecompressVideoData(int a1, void *DstBuf);
int ReadByte();
char __stdcall ReadCompressedData(char *destBuffer);
char __stdcall ReadCustomSaveData(int *data_desc);
BOOL __stdcall ReadFileData(unsigned int maxBytes, void *DstBuf);
int __stdcall ReadFileRaw(unsigned int maxBytes, void *DstBuf);
BOOL __stdcall ReadFromFile(unsigned int size, void *dst_buf);
char __stdcall ReadJumpOffset(int initialValue, size_t *outPosition);
int ReadMidiVarLen();
BOOL ReadSaveHeader();
void ReallocFrameBuffers(void);
int ReexecuteCurrentSpriteScript();
int __stdcall RemoveAndCreateTileObject(char removeStandalone, int tileY, int tileX);
int __stdcall RemoveAndFreeRenderObject(RenderObject *render_object);
int __stdcall RemoveChildTextObjects(int parent_object_addr);
int __stdcall RemoveRenderObjectByIndex(int a1);
char RenderDirtyRegions();
int __stdcall RenderFormattedText(uint16_t renderY, int renderX, int fontIndex, int textDataPtr);
int __stdcall RenderOverlaySlot(int a1);
int __stdcall RenderOverlayText(int textDataPtr, int a2);
int __stdcall RenderOverlayWithContext(int **a1);
int __stdcall RenderOverlayWithCoords(int a1);
int __stdcall RenderSprite(int useAbsoluteCoords, int *spriteData);
RenderObject *__stdcall RenderTextCharacter(uint16_t render_y, uint16_t *render_x_ptr, int font_index, int character);
char ResetGameState();
void ResetMemoryPool();
MMRESULT ResetMidi();
int ResetRenderObjects();
BOOL ResetWave();
char RestoreGraphicsAfterVideo();
void RestoreScreenAndMusic();
BOOL ResumeWave();
char __cdecl ResumeWavePlayback();
void __stdcall SafeFreeMemoryBlock(void *ptr);
char __stdcall SaveGameState(int save_slot);
char __stdcall SaveSnapshotsToFile(int a1);
char __stdcall SearchVideoFileOnDrives(char *Str, char *Destination, char *lpFileName);
BOOL __stdcall SeekFile(int Origin, int Offset);
BOOL __stdcall SeekFileWithBuffer(int Origin, int Offset);
BOOL __stdcall SeekSaveFile(int seekOffset);
int __stdcall SelectRandomAnimationFrame(char a1, int a2);
int __stdcall SendMCICommand(DWORD_PTR dwParam2, DWORD_PTR dwParam1, UINT uMsg);
DWORD_PTR __stdcall SendMCICommandSimple(DWORD_PTR result, DWORD_PTR dwParam1, UINT uMsg);
int __stdcall SetCurrentAnimationSlot(int a1);
int __stdcall SetErrorMessage(const CHAR *a1);
char __stdcall SetFrameRate(int frameRate);
int __stdcall SetMidiVolume(unsigned __int8 a1);
int __stdcall SetMusicVolume(int a1);
int __stdcall SetObjectSpriteByDirection(char a1, RenderObject *object, int a3);
BOOL __stdcall SetPalette(char a1, char a2, int cEntries, BYTE *a4);
int __stdcall SetSoundVolume(int volume);
BOOL SetVideoPalette();
int __stdcall SetWaveVolume(unsigned __int8 a1);
int SetupMemoryContext();
int __stdcall SetupPathfindPositions(unsigned __int8 search_type);
int __stdcall SetupTextDisplay(int a1, int a2, int a3, int a4);
int __stdcall ShowErrorDialog(LPCSTR lpText);
int ShowFileError();
int __stdcall ShowMessageBox(LPCSTR lpText, LPCSTR lpCaption);
void __cdecl ShutdownMultimedia();
int __stdcall StartMidiPlayback(int a1);
int __stdcall StartMusicPlayback(int a1, int a2, int param);
int __stdcall StepValueTowardTarget(unsigned __int8 target, _BYTE *current);
char __cdecl StopMidiMusic();
char StopMidiPlayback();
int __stdcall SwitchMusicTrack(int a1);
int TellSaveFile();
int __stdcall TracePathAlongWave(unsigned __int8 wave_value);
void __stdcall TransformDir_FlipHorizontal(SpriteDesc *desc);
void __stdcall TransformDir_FlipVertical(SpriteDesc *desc);
void __stdcall TransformDir_ReflectAntiDiag(SpriteDesc *desc);
void __stdcall TransformDir_ReflectDiag(SpriteDesc *desc);
void __stdcall TransformDir_Rotate180(SpriteDesc *desc);
void __stdcall TransformDir_Rotate90CCW(SpriteDesc *desc);
void __stdcall TransformDir_Rotate90CW(SpriteDesc *desc);
int __stdcall TriggerSoundSlot(int a1);
int TruncateFile();
char __stdcall UpdateCursorPosition(unsigned __int16 a1, unsigned __int16 a2);
char UpdateFrameRate();
int __stdcall UpdateObjectPosition(int a1);
int __stdcall UpdateRenderObjectBounds(RenderObject *a1);
void __stdcall UpdateRenderObjectCache(RenderObject *object);
int UpdateScreenSections();
char __stdcall UpdateSpriteAnimation(int shouldFree, int forceUpdate, RenderObject *object);
char __stdcall ValidateGameData(int a1);
LRESULT __stdcall VideoWndProc(HWND hWnd, UINT Msg, HWND wParam, _DWORD *lParam);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
HGLOBAL WinNT_CleanupMultimedia();
int WinNT_GetNextWaveBuffer();
int WinNT_PauseWave();
int WinNT_ResetWave();
int WinNT_ResumeWave();
int __stdcall WinNT_SetMidiVolume(unsigned __int8 a1);
int __stdcall WinNT_SetWaveVolume(unsigned __int8 a1);
int __stdcall WinNT_StartMidiPlayback(_DWORD *Src);
int WinNT_StopMidiPlayback();
int WinNT_WriteWaveBuffer();
char __stdcall WriteCustomSaveData(int *data_desc);
BOOL __stdcall WriteDword(unsigned int value);
int WriteSaveHeader();
BOOL __stdcall WriteToFile(unsigned int size, void *buf);
BOOL WriteWaveBuffer();
_BYTE *__stdcall XorCryptData(int cryptOffset, int size, _BYTE *data);
int __stdcall sub_407618(int a1, int a2);
int __stdcall sub_408870(int a1, int a2, int a3);

#endif /* PILOTS_GLOBALS_H */
